---
name: CI build

defaults:
  distribution: temurin
  java-version: 21

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        id: setup_jdk
        name: Setup JDK
        with:
          cache: maven

      - name: Build
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make install
