---
name: CD (Snapshot deployment)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: sonatype-central-portal
          server-username: NEXUS_REPO_USER
          server-password: NEXUS_REPO_PASSWORD

      - name: deploy code
        env:
          NEXUS_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
          NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
          MAVEN_ARGS: "-B -ff"
        run: make deploy

  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set git information
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-password: SITE_DEPLOY

      - name: deploy documentation
        env:
          SITE_DEPLOY: ${{ secrets.SITE_DEPLOY_TOKEN  }}
          MAVEN_ARGS: "-B -ff"
        run: make deploy-site
